apiVersion: kubeadm.k8s.io/v1beta2
caCertPath: /etc/kubernetes/pki/ca.crt
kind: JoinConfiguration
discovery:
  bootstrapToken:
    apiServerEndpoint: kuber-haproxy-n1:6443
    caCertHashes:
    - sha256:<hash key>
    token: <token>
  timeout: 5m0s
  tlsBootstrapToken: <token>
nodeRegistration:
  name: kuber-worker-n1
  kubeletExtraArgs:
    node-ip: 192.168.115.38